"""file_engine.py — Advanced file processing, conversion, and extraction engine."""

import io
import os
from typing import BinaryIO, Optional
import markdown2
try:
    from docx import Document
except ImportError:
    Document = None
try:
    import img2pdf
except ImportError:
    img2pdf = None

from utils.pdf_handler import extract_text_from_pdf, get_pdf_summary_stats
from utils.ocr_handler import extract_text_from_image

class FileEngine:
    @staticmethod
    def process_upload(file: BinaryIO, filename: str) -> dict:
        """Categorize and extract text/metadata from any supported file type."""
        ext = filename.split('.')[-1].lower()
        content = ""
        metadata = {}
        
        file.seek(0)
        
        if ext == 'pdf':
            content = extract_text_from_pdf(file)
            file.seek(0)
            metadata = get_pdf_summary_stats(file)
        elif ext in ['docx', 'doc']:
            content, metadata = FileEngine._extract_docx(file)
        elif ext == 'txt':
            content = file.read().decode('utf-8', errors='ignore')
            metadata = {"words": len(content.split()), "type": "Text File"}
        elif ext in ['png', 'jpg', 'jpeg']:
            content = extract_text_from_image(file.read())
            metadata = {"type": "Image (OCR)"}
            
        return {
            "text": content,
            "meta": metadata,
            "filename": filename,
            "extension": ext
        }

    @staticmethod
    def _extract_docx(file: BinaryIO) -> tuple[str, dict]:
        if Document is None:
            return "Error: python-docx not installed.", {}
        try:
            doc = Document(file)
            full_text = []
            for para in doc.paragraphs:
                full_text.append(para.text)
            text = "\n".join(full_text)
            return text, {"words": len(text.split()), "paragraphs": len(doc.paragraphs), "type": "Word Document"}
        except Exception as e:
            return f"Error: {e}", {}

    @staticmethod
    def generate_html_notes(title: str, markdown_content: str) -> str:
        """Convert Study AI markdown output into a beautiful standalone HTML study page."""
        html_body = markdown2.markdown(markdown_content, extras=["tables", "fenced-code-blocks"])
        template = f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>{title}</title>
            <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&family=JetBrains+Mono&display=swap" rel="stylesheet">
            <style>
                :root {{ --bg: #0c0a09; --text: #f5f5f4; --accent: #FF8C00; --card: #1c1917; }}
                body {{ font-family: 'Inter', sans-serif; background: var(--bg); color: var(--text); line-height: 1.6; padding: 2rem; max-width: 800px; margin: 0 auto; }}
                h1, h2, h3 {{ color: var(--accent); letter-spacing: -0.02em; }}
                .container {{ background: var(--card); padding: 2rem; border-radius: 12px; border: 1px solid #292524; box-shadow: 0 10px 30px rgba(0,0,0,0.5); }}
                code {{ font-family: 'JetBrains Mono', monospace; background: #292524; padding: 0.2rem 0.4rem; border-radius: 4px; font-size: 0.9em; }}
                pre {{ background: #1c1917; padding: 1rem; border-radius: 8px; overflow-x: auto; border: 1px solid #444; }}
                table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; }}
                th, td {{ border: 1px solid #444; padding: 8px; text-align: left; }}
                th {{ background: #292524; }}
            </style>
        </head>
        <body>
            <div class="container">
                <h1>{title}</h1>
                <hr style="border:0; border-top:1px solid #444; margin: 1.5rem 0;">
                {html_body}
            </div>
            <footer style="text-align:center; margin-top: 2rem; font-size: 0.8rem; color: #78716c;">
                Generated by ExamHelp AI • {title} • Study Session
            </footer>
        </body>
        </html>
        """
        return template

    @staticmethod
    def images_to_pdf(image_list: list[bytes]) -> Optional[bytes]:
        """Convert a list of scanned image bytes into a single compiled PDF study guide."""
        if img2pdf is None:
            return None
        try:
            return img2pdf.convert(image_list)
        except Exception:
            return None
