"""study_generator.py — Multi-format Study Material Generation Engine.

Supports PDF, DOCX, PPT, and HTML generation from AI-provided study content.
"""

import io
from typing import Optional
from fpdf import FPDF
from docx import Document
from pptx import Presentation
from pptx.util import Inches, Pt
import markdown2

class StudyGenerator:
    @staticmethod
    def generate_pdf(title: str, content: str) -> bytes:
        """Generate a clean, paginated PDF study guide with Unicode safety."""
        pdf = FPDF()
        pdf.add_page()
        
        # Header - Font Setup (Arial is a safe alias for Helvetica in fpdf2)
        pdf.set_font("Arial", "B", 18)
        # Clean title for Latin-1
        safe_title = title.encode('latin-1', 'ignore').decode('latin-1')
        pdf.cell(0, 15, safe_title, ln=True, align="C")
        pdf.ln(10)
        
        # Body Content
        pdf.set_font("Arial", size=11)
        
        # 1. Strip Markdown noise
        clean_text = content.replace("##", "").replace("#", "").replace("**", "")
        
        # 2. CRITICAL FIX: Strip non-Latin-1 characters (Emojis, non-Western chars)
        # Standard fonts in FPDF only support Latin-1 range.
        safe_body = clean_text.encode('latin-1', 'ignore').decode('latin-1')
        
        pdf.multi_cell(0, 7, safe_body)
        
        # FPDF2 output(dest='S') returns a bytearray/bytes object
        return bytes(pdf.output(dest='S'))

    @staticmethod
    def generate_docx(title: str, content: str) -> bytes:
        """Generate a professionally formatted Word document."""
        doc = Document()
        doc.add_heading(title, 0)
        
        # Split by sections for better formatting
        sections = content.split("##")
        for section in sections:
            if not section.strip(): continue
            lines = section.strip().split("\n")
            doc.add_heading(lines[0], level=1)
            doc.add_paragraph("\n".join(lines[1:]))
            
        file_stream = io.BytesIO()
        doc.save(file_stream)
        return file_stream.getvalue()

    @staticmethod
    def generate_ppt(title: str, content: str) -> bytes:
        """Generate a multi-slide PowerPoint presentation."""
        prs = Presentation()
        
        # Title Slide
        title_slide = prs.slides.add_slide(prs.slide_layouts[0])
        title_slide.shapes.title.text = title
        title_slide.placeholders[1].text = "Generated by ExamHelp Study AI"
        
        # Content Slides split by markdown headers
        sections = content.split("##")
        for section in sections:
            if len(section.strip()) < 10: continue
            lines = section.strip().split("\n")
            slide = prs.slides.add_slide(prs.slide_layouts[1])
            slide.shapes.title.text = lines[0]
            slide.placeholders[1].text = "\n".join(lines[1:10]) # Limit text per slide
            
        file_stream = io.BytesIO()
        prs.save(file_stream)
        return file_stream.getvalue()

    @staticmethod
    def generate_html(title: str, content: str) -> str:
        """Generate a glassmorphic study website (Standalone HTML)."""
        html_content = markdown2.markdown(content, extras=["tables", "fenced-code-blocks"])
        template = f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>{title}</title>
            <style>
                body {{ font-family: system-ui; background: #0c0a09; color: #f5f5f4; padding: 50px; line-height: 1.6; }}
                .container {{ max-width: 900px; margin: auto; background: #1c1917; padding: 40px; border-radius: 20px; border: 1px solid #444; }}
                h1, h2 {{ color: #FF8C00; }}
                pre {{ background: #292524; padding: 20px; border-radius: 10px; overflow-x: auto; }}
                table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
                th, td {{ border: 1px solid #444; padding: 12px; text-align: left; }}
            </style>
        </head>
        <body>
            <div class="container">
                <h1>{title}</h1>
                <hr style="opacity: 0.2; margin: 30px 0;">
                {html_content}
            </div>
        </body>
        </html>
        """
        return template
